services:
  - docker

branches:
  only:
    - main

before_install:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed ghostscypher/udagram-api-feed:v1
  - docker tag udagram-api-user ghostscypher/udagram-api-user:v1
  - docker tag udagram-frontend ghostscypher/udagram-frontend:v1
  - docker tag udagram-reverseproxy ghostscypher/reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ghostscypher/udagram-api-feed:v1
  - docker push ghostscypher/udagram-api-user:v1
  - docker push ghostscypher/udagram-frontend:v1
  - docker push ghostscypher/reverseproxy:v1

  