apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
        - name: frontend
          image: ghostscypher/udagram-frontend:v5
          ports:
            - containerPort: 80
          env:
          - name: BACKEND_API_HOST
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: BACKEND_API_HOST
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always
